---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: null
  labels:
    app: backstage
  name: backstage
spec:
  lookupPolicy:
    local: true
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: null
  labels:
    app: backstage
  name: backstage
spec:
  resources:
    limits:
      cpu: "300m"
      memory: "1Gi"
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: backstage:latest
  postCommit: {}
  runPolicy: Serial
  source:
    git:
      ref: main
      uri: https://github.com/redhat-developer/redhat-backstage-build.git
    type: Git
    contextDir: .
  strategy:
    dockerStrategy:
      dockerfilePath: Dockerfile
    type: Docker
  successfulBuildsHistoryLimit: 5
  triggers:
  - github:
      secret: 7uqdp8XlkT-IteMISzpt
    type: GitHub
  - generic:
      secret: gR5-Dtb1Ie_6ILQrEcWd
    type: Generic
  - type: ConfigChange
